# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerPath.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Origin_pb2 as Origin__pb2
from . import NowPlayingClient_pb2 as NowPlayingClient__pb2
from . import NowPlayingPlayer_pb2 as NowPlayingPlayer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerPath.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10PlayerPath.proto\x1a\x0cOrigin.proto\x1a\x16NowPlayingClient.proto\x1a\x16NowPlayingPlayer.proto\"k\n\nPlayerPath\x12\x17\n\x06origin\x18\x01 \x01(\x0b\x32\x07.Origin\x12!\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x11.NowPlayingClient\x12!\n\x06player\x18\x03 \x01(\x0b\x32\x11.NowPlayingPlayer')
  ,
  dependencies=[Origin__pb2.DESCRIPTOR,NowPlayingClient__pb2.DESCRIPTOR,NowPlayingPlayer__pb2.DESCRIPTOR,])




_PLAYERPATH = _descriptor.Descriptor(
  name='PlayerPath',
  full_name='PlayerPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='PlayerPath.origin', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client', full_name='PlayerPath.client', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='PlayerPath.player', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=189,
)

_PLAYERPATH.fields_by_name['origin'].message_type = Origin__pb2._ORIGIN
_PLAYERPATH.fields_by_name['client'].message_type = NowPlayingClient__pb2._NOWPLAYINGCLIENT
_PLAYERPATH.fields_by_name['player'].message_type = NowPlayingPlayer__pb2._NOWPLAYINGPLAYER
DESCRIPTOR.message_types_by_name['PlayerPath'] = _PLAYERPATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerPath = _reflection.GeneratedProtocolMessageType('PlayerPath', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPATH,
  __module__ = 'PlayerPath_pb2'
  # @@protoc_insertion_point(class_scope:PlayerPath)
  ))
_sym_db.RegisterMessage(PlayerPath)


# @@protoc_insertion_point(module_scope)
