# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoveClientMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as ProtocolMessage__pb2
from . import NowPlayingClient_pb2 as NowPlayingClient__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RemoveClientMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19RemoveClientMessage.proto\x1a\x15ProtocolMessage.proto\x1a\x16NowPlayingClient.proto\"8\n\x13RemoveClientMessage\x12!\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x11.NowPlayingClient:C\n\x13removeClientMessage\x12\x10.ProtocolMessage\x18\x39 \x01(\x0b\x32\x14.RemoveClientMessage')
  ,
  dependencies=[ProtocolMessage__pb2.DESCRIPTOR,NowPlayingClient__pb2.DESCRIPTOR,])


REMOVECLIENTMESSAGE_FIELD_NUMBER = 57
removeClientMessage = _descriptor.FieldDescriptor(
  name='removeClientMessage', full_name='removeClientMessage', index=0,
  number=57, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_REMOVECLIENTMESSAGE = _descriptor.Descriptor(
  name='RemoveClientMessage',
  full_name='RemoveClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='RemoveClientMessage.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=132,
)

_REMOVECLIENTMESSAGE.fields_by_name['client'].message_type = NowPlayingClient__pb2._NOWPLAYINGCLIENT
DESCRIPTOR.message_types_by_name['RemoveClientMessage'] = _REMOVECLIENTMESSAGE
DESCRIPTOR.extensions_by_name['removeClientMessage'] = removeClientMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoveClientMessage = _reflection.GeneratedProtocolMessageType('RemoveClientMessage', (_message.Message,), dict(
  DESCRIPTOR = _REMOVECLIENTMESSAGE,
  __module__ = 'RemoveClientMessage_pb2'
  # @@protoc_insertion_point(class_scope:RemoveClientMessage)
  ))
_sym_db.RegisterMessage(RemoveClientMessage)

removeClientMessage.message_type = _REMOVECLIENTMESSAGE
ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(removeClientMessage)

# @@protoc_insertion_point(module_scope)
