# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendButtonEventMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as ProtocolMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SendButtonEventMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1cSendButtonEventMessage.proto\x1a\x15ProtocolMessage.proto\"N\n\x16SendButtonEventMessage\x12\x11\n\tusagePage\x18\x01 \x01(\r\x12\r\n\x05usage\x18\x02 \x01(\r\x12\x12\n\nbuttonDown\x18\x03 \x01(\x08:I\n\x16sendButtonEventMessage\x12\x10.ProtocolMessage\x18+ \x01(\x0b\x32\x17.SendButtonEventMessage')
  ,
  dependencies=[ProtocolMessage__pb2.DESCRIPTOR,])


SENDBUTTONEVENTMESSAGE_FIELD_NUMBER = 43
sendButtonEventMessage = _descriptor.FieldDescriptor(
  name='sendButtonEventMessage', full_name='sendButtonEventMessage', index=0,
  number=43, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SENDBUTTONEVENTMESSAGE = _descriptor.Descriptor(
  name='SendButtonEventMessage',
  full_name='SendButtonEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usagePage', full_name='SendButtonEventMessage.usagePage', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage', full_name='SendButtonEventMessage.usage', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buttonDown', full_name='SendButtonEventMessage.buttonDown', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['SendButtonEventMessage'] = _SENDBUTTONEVENTMESSAGE
DESCRIPTOR.extensions_by_name['sendButtonEventMessage'] = sendButtonEventMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendButtonEventMessage = _reflection.GeneratedProtocolMessageType('SendButtonEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENDBUTTONEVENTMESSAGE,
  __module__ = 'SendButtonEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:SendButtonEventMessage)
  ))
_sym_db.RegisterMessage(SendButtonEventMessage)

sendButtonEventMessage.message_type = _SENDBUTTONEVENTMESSAGE
ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(sendButtonEventMessage)

# @@protoc_insertion_point(module_scope)
