# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendVirtualTouchEventMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as ProtocolMessage__pb2
from . import VirtualTouchEvent_pb2 as VirtualTouchEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SendVirtualTouchEventMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\"SendVirtualTouchEventMessage.proto\x1a\x15ProtocolMessage.proto\x1a\x17VirtualTouchEvent.proto\"[\n\x1cSendVirtualTouchEventMessage\x12\x18\n\x10\x64\x65viceIdentifier\x18\x01 \x01(\x05\x12!\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x12.VirtualTouchEvent:U\n\x1csendVirtualTouchEventMessage\x12\x10.ProtocolMessage\x18\x0f \x01(\x0b\x32\x1d.SendVirtualTouchEventMessage')
  ,
  dependencies=[ProtocolMessage__pb2.DESCRIPTOR,VirtualTouchEvent__pb2.DESCRIPTOR,])


SENDVIRTUALTOUCHEVENTMESSAGE_FIELD_NUMBER = 15
sendVirtualTouchEventMessage = _descriptor.FieldDescriptor(
  name='sendVirtualTouchEventMessage', full_name='sendVirtualTouchEventMessage', index=0,
  number=15, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SENDVIRTUALTOUCHEVENTMESSAGE = _descriptor.Descriptor(
  name='SendVirtualTouchEventMessage',
  full_name='SendVirtualTouchEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceIdentifier', full_name='SendVirtualTouchEventMessage.deviceIdentifier', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='SendVirtualTouchEventMessage.event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=177,
)

_SENDVIRTUALTOUCHEVENTMESSAGE.fields_by_name['event'].message_type = VirtualTouchEvent__pb2._VIRTUALTOUCHEVENT
DESCRIPTOR.message_types_by_name['SendVirtualTouchEventMessage'] = _SENDVIRTUALTOUCHEVENTMESSAGE
DESCRIPTOR.extensions_by_name['sendVirtualTouchEventMessage'] = sendVirtualTouchEventMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendVirtualTouchEventMessage = _reflection.GeneratedProtocolMessageType('SendVirtualTouchEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENDVIRTUALTOUCHEVENTMESSAGE,
  __module__ = 'SendVirtualTouchEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:SendVirtualTouchEventMessage)
  ))
_sym_db.RegisterMessage(SendVirtualTouchEventMessage)

sendVirtualTouchEventMessage.message_type = _SENDVIRTUALTOUCHEVENTMESSAGE
ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(sendVirtualTouchEventMessage)

# @@protoc_insertion_point(module_scope)
