# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetDefaultSupportedCommandsMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as ProtocolMessage__pb2
from . import SupportedCommands_pb2 as SupportedCommands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SetDefaultSupportedCommandsMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n(SetDefaultSupportedCommandsMessage.proto\x1a\x15ProtocolMessage.proto\x1a\x17SupportedCommands.proto\"f\n\"SetDefaultSupportedCommandsMessage\x12-\n\x11supportedCommands\x18\x02 \x01(\x0b\x32\x12.SupportedCommands\x12\x11\n\tdisplayID\x18\x04 \x01(\t:a\n\"setDefaultSupportedCommandsMessage\x12\x10.ProtocolMessage\x18K \x01(\x0b\x32#.SetDefaultSupportedCommandsMessage')
  ,
  dependencies=[ProtocolMessage__pb2.DESCRIPTOR,SupportedCommands__pb2.DESCRIPTOR,])


SETDEFAULTSUPPORTEDCOMMANDSMESSAGE_FIELD_NUMBER = 75
setDefaultSupportedCommandsMessage = _descriptor.FieldDescriptor(
  name='setDefaultSupportedCommandsMessage', full_name='setDefaultSupportedCommandsMessage', index=0,
  number=75, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SETDEFAULTSUPPORTEDCOMMANDSMESSAGE = _descriptor.Descriptor(
  name='SetDefaultSupportedCommandsMessage',
  full_name='SetDefaultSupportedCommandsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supportedCommands', full_name='SetDefaultSupportedCommandsMessage.supportedCommands', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayID', full_name='SetDefaultSupportedCommandsMessage.displayID', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=194,
)

_SETDEFAULTSUPPORTEDCOMMANDSMESSAGE.fields_by_name['supportedCommands'].message_type = SupportedCommands__pb2._SUPPORTEDCOMMANDS
DESCRIPTOR.message_types_by_name['SetDefaultSupportedCommandsMessage'] = _SETDEFAULTSUPPORTEDCOMMANDSMESSAGE
DESCRIPTOR.extensions_by_name['setDefaultSupportedCommandsMessage'] = setDefaultSupportedCommandsMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetDefaultSupportedCommandsMessage = _reflection.GeneratedProtocolMessageType('SetDefaultSupportedCommandsMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETDEFAULTSUPPORTEDCOMMANDSMESSAGE,
  __module__ = 'SetDefaultSupportedCommandsMessage_pb2'
  # @@protoc_insertion_point(class_scope:SetDefaultSupportedCommandsMessage)
  ))
_sym_db.RegisterMessage(SetDefaultSupportedCommandsMessage)

setDefaultSupportedCommandsMessage.message_type = _SETDEFAULTSUPPORTEDCOMMANDSMESSAGE
ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(setDefaultSupportedCommandsMessage)

# @@protoc_insertion_point(module_scope)
