# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetStateMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as ProtocolMessage__pb2
from . import NowPlayingInfo_pb2 as NowPlayingInfo__pb2
from . import SupportedCommands_pb2 as SupportedCommands__pb2
from . import PlayerPath_pb2 as PlayerPath__pb2
from . import PlaybackQueue_pb2 as PlaybackQueue__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SetStateMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15SetStateMessage.proto\x1a\x15ProtocolMessage.proto\x1a\x14NowPlayingInfo.proto\x1a\x17SupportedCommands.proto\x1a\x10PlayerPath.proto\x1a\x13PlaybackQueue.proto\"\x92\x03\n\x0fSetStateMessage\x12\'\n\x0enowPlayingInfo\x18\x01 \x01(\x0b\x32\x0f.NowPlayingInfo\x12-\n\x11supportedCommands\x18\x02 \x01(\x0b\x32\x12.SupportedCommands\x12%\n\rplaybackQueue\x18\x03 \x01(\x0b\x32\x0e.PlaybackQueue\x12\x11\n\tdisplayID\x18\x04 \x01(\t\x12\x13\n\x0b\x64isplayName\x18\x05 \x01(\t\x12\x35\n\rplaybackState\x18\x06 \x01(\x0e\x32\x1e.SetStateMessage.PlaybackState\x12\x1f\n\nplayerPath\x18\t \x01(\x0b\x32\x0b.PlayerPath\x12\x1e\n\x16playbackStateTimestamp\x18\x0b \x01(\x01\"`\n\rPlaybackState\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Playing\x10\x01\x12\n\n\x06Paused\x10\x02\x12\x0b\n\x07Stopped\x10\x03\x12\x0f\n\x0bInterrupted\x10\x04\x12\x0b\n\x07Seeking\x10\x05:;\n\x0fsetStateMessage\x12\x10.ProtocolMessage\x18\t \x01(\x0b\x32\x10.SetStateMessage')
  ,
  dependencies=[ProtocolMessage__pb2.DESCRIPTOR,NowPlayingInfo__pb2.DESCRIPTOR,SupportedCommands__pb2.DESCRIPTOR,PlayerPath__pb2.DESCRIPTOR,PlaybackQueue__pb2.DESCRIPTOR,])


SETSTATEMESSAGE_FIELD_NUMBER = 9
setStateMessage = _descriptor.FieldDescriptor(
  name='setStateMessage', full_name='setStateMessage', index=0,
  number=9, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_SETSTATEMESSAGE_PLAYBACKSTATE = _descriptor.EnumDescriptor(
  name='PlaybackState',
  full_name='SetStateMessage.PlaybackState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Playing', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Paused', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Stopped', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Interrupted', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Seeking', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=441,
  serialized_end=537,
)
_sym_db.RegisterEnumDescriptor(_SETSTATEMESSAGE_PLAYBACKSTATE)


_SETSTATEMESSAGE = _descriptor.Descriptor(
  name='SetStateMessage',
  full_name='SetStateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nowPlayingInfo', full_name='SetStateMessage.nowPlayingInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supportedCommands', full_name='SetStateMessage.supportedCommands', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playbackQueue', full_name='SetStateMessage.playbackQueue', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayID', full_name='SetStateMessage.displayID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='SetStateMessage.displayName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playbackState', full_name='SetStateMessage.playbackState', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerPath', full_name='SetStateMessage.playerPath', index=6,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playbackStateTimestamp', full_name='SetStateMessage.playbackStateTimestamp', index=7,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETSTATEMESSAGE_PLAYBACKSTATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=537,
)

_SETSTATEMESSAGE.fields_by_name['nowPlayingInfo'].message_type = NowPlayingInfo__pb2._NOWPLAYINGINFO
_SETSTATEMESSAGE.fields_by_name['supportedCommands'].message_type = SupportedCommands__pb2._SUPPORTEDCOMMANDS
_SETSTATEMESSAGE.fields_by_name['playbackQueue'].message_type = PlaybackQueue__pb2._PLAYBACKQUEUE
_SETSTATEMESSAGE.fields_by_name['playbackState'].enum_type = _SETSTATEMESSAGE_PLAYBACKSTATE
_SETSTATEMESSAGE.fields_by_name['playerPath'].message_type = PlayerPath__pb2._PLAYERPATH
_SETSTATEMESSAGE_PLAYBACKSTATE.containing_type = _SETSTATEMESSAGE
DESCRIPTOR.message_types_by_name['SetStateMessage'] = _SETSTATEMESSAGE
DESCRIPTOR.extensions_by_name['setStateMessage'] = setStateMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetStateMessage = _reflection.GeneratedProtocolMessageType('SetStateMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETSTATEMESSAGE,
  __module__ = 'SetStateMessage_pb2'
  # @@protoc_insertion_point(class_scope:SetStateMessage)
  ))
_sym_db.RegisterMessage(SetStateMessage)

setStateMessage.message_type = _SETSTATEMESSAGE
ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(setStateMessage)

# @@protoc_insertion_point(module_scope)
