# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TextInputTraits.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TextInputTraits.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15TextInputTraits.proto\"\xe2\x03\n\x0fTextInputTraits\"L\n\x16\x41utocapitalizationType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05WORDS\x10\x01\x12\r\n\tSENTENCES\x10\x02\x12\x0e\n\nCHARACTERS\x10\x03\"\xd6\x01\n\x0cKeyboardType\x12\x19\n\x15KEYBOARD_TYPE_DEFAULT\x10\x00\x12\x11\n\rASCII_CAPABLE\x10\x01\x12\x1b\n\x17NUMBERS_AND_PUNCTUATION\x10\x02\x12\x07\n\x03URL\x10\x03\x12\x0e\n\nNUMBER_PAD\x10\x04\x12\r\n\tPHONE_PAD\x10\x05\x12\x12\n\x0eNAME_PHONE_PAD\x10\x06\x12\x11\n\rEMAIL_ADDRESS\x10\x07\x12\x0f\n\x0b\x44\x45\x43IMAL_PAD\x10\x08\x12\x0b\n\x07TWITTER\x10\t\x12\x0e\n\nWEB_SEARCH\x10\n\"\xa7\x01\n\rReturnKeyType\x12\x16\n\x12RETURN_KEY_DEFAULT\x10\x00\x12\x06\n\x02GO\x10\x01\x12\n\n\x06GOOGLE\x10\x02\x12\x08\n\x04JOIN\x10\x03\x12\x08\n\x04NEXT\x10\x04\x12\t\n\x05ROUTE\x10\x05\x12\n\n\x06SEARCH\x10\x06\x12\x08\n\x04SEND\x10\x07\x12\t\n\x05YAHOO\x10\x08\x12\x08\n\x04\x44ONE\x10\t\x12\x12\n\x0e\x45MERGENCY_CALL\x10\n\x12\x0c\n\x08\x43ONTINUE\x10\x0b')
)



_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE = _descriptor.EnumDescriptor(
  name='AutocapitalizationType',
  full_name='TextInputTraits.AutocapitalizationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORDS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENTENCES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHARACTERS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=45,
  serialized_end=121,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE)

_TEXTINPUTTRAITS_KEYBOARDTYPE = _descriptor.EnumDescriptor(
  name='KeyboardType',
  full_name='TextInputTraits.KeyboardType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEYBOARD_TYPE_DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASCII_CAPABLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMBERS_AND_PUNCTUATION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMBER_PAD', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE_PAD', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAME_PHONE_PAD', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMAIL_ADDRESS', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECIMAL_PAD', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWITTER', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB_SEARCH', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_KEYBOARDTYPE)

_TEXTINPUTTRAITS_RETURNKEYTYPE = _descriptor.EnumDescriptor(
  name='ReturnKeyType',
  full_name='TextInputTraits.ReturnKeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RETURN_KEY_DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEXT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUTE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YAHOO', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY_CALL', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=341,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_RETURNKEYTYPE)


_TEXTINPUTTRAITS = _descriptor.Descriptor(
  name='TextInputTraits',
  full_name='TextInputTraits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE,
    _TEXTINPUTTRAITS_KEYBOARDTYPE,
    _TEXTINPUTTRAITS_RETURNKEYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=508,
)

_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE.containing_type = _TEXTINPUTTRAITS
_TEXTINPUTTRAITS_KEYBOARDTYPE.containing_type = _TEXTINPUTTRAITS
_TEXTINPUTTRAITS_RETURNKEYTYPE.containing_type = _TEXTINPUTTRAITS
DESCRIPTOR.message_types_by_name['TextInputTraits'] = _TEXTINPUTTRAITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextInputTraits = _reflection.GeneratedProtocolMessageType('TextInputTraits', (_message.Message,), dict(
  DESCRIPTOR = _TEXTINPUTTRAITS,
  __module__ = 'TextInputTraits_pb2'
  # @@protoc_insertion_point(class_scope:TextInputTraits)
  ))
_sym_db.RegisterMessage(TextInputTraits)


# @@protoc_insertion_point(module_scope)
